language: php
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.3
      env: PREFER_LOWEST=""
    - php: 7.2
      env: PREFER_LOWEST=""
    - php: 7.1
      env: PREFER_LOWEST=""
    - php: 7.1
      env: PREFER_LOWEST="--prefer-lowest"

before_script:
- composer update --prefer-dist $PREFER_LOWEST
script:
- "./vendor/bin/phpunit"
- composer phpstan
after_script:
- if [ -z "$PREFER_LOWEST" ]; then ./vendor/bin/coveralls -v; fi
