language: php
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.3
      env: PREFER_LOWEST=""
      before_script:
        - &composerupdate
          composer update --prefer-dist $PREFER_LOWEST
      script:
        - &phpunit
          "./vendor/bin/phpunit"
        - composer phpstan
      after_script:
        - ./vendor/bin/coveralls -v
    - php: 7.2
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - php: 7.1
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - php: 7.1
      env: PREFER_LOWEST="--prefer-lowest"
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - name: "Doc generation"
      language: node_js
      node_js: 8
      branches:
        only:
          - master
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
